# DO-NOT-EDIT: Generated by github:vic/flake-file.
# To re-generate use: nix-shell . -A flake-file.sh --run write-inputs
{
  den.url = "github:denful/den";
  disko = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/disko";
  };
  firefox-addons = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "gitlab:rycee/nur-expressions?dir=pkgs/firefox-addons";
  };
  flake-file.url = "github:vic/flake-file";
  flake-parts = {
    inputs.nixpkgs-lib.follows = "nixpkgs";
    url = "github:hercules-ci/flake-parts";
  };
  globalprotect-openconnect.url = "github:yuezk/GlobalProtect-openconnect";
  helium-flake = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:oxcl/nix-flake-helium-browser";
  };
  home-manager = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/home-manager";
  };
  import-tree.url = "github:vic/import-tree";
  niri = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:epireyn/niri-flake";
  };
  nix-doom-emacs-unstraightened = {
    inputs.nixpkgs.follows = "";
    url = "github:marienz/nix-doom-emacs-unstraightened";
  };
  nixpkgs.url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz";
  noctalia.url = "github:noctalia-dev/noctalia/cachix";
  noctalia-greeter = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:noctalia-dev/noctalia-greeter";
  };
  sops-nix = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:Mic92/sops-nix";
  };
  spicetify-nix = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:Gerg-L/spicetify-nix";
  };
  stylix = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/stylix";
  };
  zen-browser = {
    inputs = {
      home-manager.follows = "home-manager";
      nixpkgs.follows = "nixpkgs";
    };
    url = "github:0xc000022070/zen-browser-flake";
  };
}
